-- Data for testing purposes
INSERT INTO public.location_area(id, code, description) VALUES(1, 'ES-La Coruña', 'La Coruña');
INSERT INTO public.location_area(id, code, description) VALUES(2, 'ES-Álava', 'Álava');
INSERT INTO public.location_area(id, code, description) VALUES(3, 'ES-Albacete', 'Albacete');
INSERT INTO public.location_area(id, code, description) VALUES(4, 'ES-Alicante', 'Alicante');
INSERT INTO public.location_area(id, code, description) VALUES(5, 'ES-Almería', 'Almería');
INSERT INTO public.location_area(id, code, description) VALUES(6, 'ES-Asturias', 'Asturias');
INSERT INTO public.location_area(id, code, description) VALUES(7, 'ES-Ávila', 'Ávila');
INSERT INTO public.location_area(id, code, description) VALUES(8, 'ES-Badajoz', 'Badajoz');
INSERT INTO public.location_area(id, code, description) VALUES(9, 'ES-Balearic Islands', 'Balearic Islands');
INSERT INTO public.location_area(id, code, description) VALUES(10, 'ES-Barcelona', 'Barcelona');
INSERT INTO public.location_area(id, code, description) VALUES(11, 'ES-Biscay', 'Biscay');
INSERT INTO public.location_area(id, code, description) VALUES(12, 'ES-Burgos', 'Burgos');
INSERT INTO public.location_area(id, code, description) VALUES(13, 'ES-Cáceres', 'Cáceres');
INSERT INTO public.location_area(id, code, description) VALUES(14, 'ES-Cádiz', 'Cádiz');
INSERT INTO public.location_area(id, code, description) VALUES(15, 'ES-Cantabria', 'Cantabria');
INSERT INTO public.location_area(id, code, description) VALUES(16, 'ES-Castellón', 'Castellón');
INSERT INTO public.location_area(id, code, description) VALUES(17, 'ES-Ciudad Real', 'Ciudad Real');
INSERT INTO public.location_area(id, code, description) VALUES(18, 'ES-Córdoba', 'Córdoba');
INSERT INTO public.location_area(id, code, description) VALUES(19, 'ES-Cuenca', 'Cuenca');
INSERT INTO public.location_area(id, code, description) VALUES(20, 'ES-Gipuzkoa', 'Gipuzkoa');
INSERT INTO public.location_area(id, code, description) VALUES(21, 'ES-Girona', 'Girona');
INSERT INTO public.location_area(id, code, description) VALUES(22, 'ES-Granada', 'Granada');
INSERT INTO public.location_area(id, code, description) VALUES(23, 'ES-Guadalajara', 'Guadalajara');
INSERT INTO public.location_area(id, code, description) VALUES(24, 'ES-Huelva', 'Huelva');
INSERT INTO public.location_area(id, code, description) VALUES(25, 'ES-Huesca', 'Huesca');
INSERT INTO public.location_area(id, code, description) VALUES(26, 'ES-Jaén', 'Jaén');
INSERT INTO public.location_area(id, code, description) VALUES(27, 'ES-La Rioja', 'La Rioja');
INSERT INTO public.location_area(id, code, description) VALUES(28, 'ES-Las Palmas', 'Las Palmas');
INSERT INTO public.location_area(id, code, description) VALUES(29, 'ES-León', 'León');
INSERT INTO public.location_area(id, code, description) VALUES(30, 'ES-Lleida', 'Lleida');
INSERT INTO public.location_area(id, code, description) VALUES(31, 'ES-Lugo', 'Lugo');
INSERT INTO public.location_area(id, code, description) VALUES(32, 'ES-Madrid', 'Madrid');
INSERT INTO public.location_area(id, code, description) VALUES(33, 'ES-Málaga', 'Málaga');
INSERT INTO public.location_area(id, code, description) VALUES(34, 'ES-Murcia', 'Murcia');
INSERT INTO public.location_area(id, code, description) VALUES(35, 'ES-Navarre', 'Navarre');
INSERT INTO public.location_area(id, code, description) VALUES(36, 'ES-Ourense', 'Ourense');
INSERT INTO public.location_area(id, code, description) VALUES(37, 'ES-Palencia', 'Palencia');
INSERT INTO public.location_area(id, code, description) VALUES(38, 'ES-Pontevedra', 'Pontevedra');
INSERT INTO public.location_area(id, code, description) VALUES(39, 'ES-Salamanca', 'Salamanca');
INSERT INTO public.location_area(id, code, description) VALUES(40, 'ES-Santa Cruz de Tenerife', 'Santa Cruz de Tenerife');
INSERT INTO public.location_area(id, code, description) VALUES(41, 'ES-Segovia', 'Segovia');
INSERT INTO public.location_area(id, code, description) VALUES(42, 'ES-Seville', 'Seville');
INSERT INTO public.location_area(id, code, description) VALUES(43, 'ES-Soria', 'Soria');
INSERT INTO public.location_area(id, code, description) VALUES(44, 'ES-Tarragona', 'Tarragona');
INSERT INTO public.location_area(id, code, description) VALUES(45, 'ES-Teruel', 'Teruel');
INSERT INTO public.location_area(id, code, description) VALUES(46, 'ES-Toledo', 'Toledo');
INSERT INTO public.location_area(id, code, description) VALUES(47, 'ES-Valencia', 'Valencia');
INSERT INTO public.location_area(id, code, description) VALUES(48, 'ES-Valladolid', 'Valladolid');
INSERT INTO public.location_area(id, code, description) VALUES(49, 'ES-Zamora', 'Zamora');
INSERT INTO public.location_area(id, code, description) VALUES(50, 'ES-Zaragoza', 'Zaragoza');
INSERT INTO public.location_area(id, code, description) VALUES(51, 'PT-Lisbon', 'Lisbon');
INSERT INTO public.location_area(id, code, description) VALUES(52, 'PT-Leiria', 'Leiria');
INSERT INTO public.location_area(id, code, description) VALUES(53, 'PT-Santarém', 'Santarém');
INSERT INTO public.location_area(id, code, description) VALUES(54, 'PT-Setúbal', 'Setúbal');
INSERT INTO public.location_area(id, code, description) VALUES(55, 'PT-Beja', 'Beja');
INSERT INTO public.location_area(id, code, description) VALUES(56, 'PT-Faro', 'Faro');
INSERT INTO public.location_area(id, code, description) VALUES(57, 'PT-Évora', 'Évora');
INSERT INTO public.location_area(id, code, description) VALUES(58, 'PT-Portalegre', 'Portalegre');
INSERT INTO public.location_area(id, code, description) VALUES(59, 'PT-Portalegre', 'Portalegre');
INSERT INTO public.location_area(id, code, description) VALUES(60, 'PT-Castelo Branco', 'Castelo Branco');
INSERT INTO public.location_area(id, code, description) VALUES(61, 'PT-Guarda', 'Guarda');
INSERT INTO public.location_area(id, code, description) VALUES(62, 'PT-Coimbra', 'Coimbra');
INSERT INTO public.location_area(id, code, description) VALUES(63, 'PT-Aveiro', 'Aveiro');
INSERT INTO public.location_area(id, code, description) VALUES(64, 'PT-Viseu', 'Viseu');
INSERT INTO public.location_area(id, code, description) VALUES(65, 'PT-Bragança', 'Bragança');
INSERT INTO public.location_area(id, code, description) VALUES(66, 'PT-Vila Real', 'Vila Real');
INSERT INTO public.location_area(id, code, description) VALUES(67, 'PT-Porto', 'Porto');
INSERT INTO public.location_area(id, code, description) VALUES(68, 'PT-Braga', 'Braga');
INSERT INTO public.location_area(id, code, description) VALUES(69, 'PT-Viana do Castelo', 'Viana do Castelo');
INSERT INTO public.location_area(id, code, description) VALUES(70, 'IT-Abruzzo', 'Abruzzo');
INSERT INTO public.location_area(id, code, description) VALUES(71, 'IT-Valle dAosta', 'Valle dAosta');
INSERT INTO public.location_area(id, code, description) VALUES(72, 'IT-Puglia', 'Puglia');
INSERT INTO public.location_area(id, code, description) VALUES(73, 'IT-Basilicata', 'Basilicata');
INSERT INTO public.location_area(id, code, description) VALUES(74, 'IT-Calabria', 'Calabria');
INSERT INTO public.location_area(id, code, description) VALUES(75, 'IT-Campania', 'Campania');
INSERT INTO public.location_area(id, code, description) VALUES(76, 'IT-Emilia-Romagna', 'Emilia-Romagna');
INSERT INTO public.location_area(id, code, description) VALUES(77, 'IT-Friuli-Venezia Giulia', 'Friuli-Venezia Giulia');
INSERT INTO public.location_area(id, code, description) VALUES(78, 'IT-Lazio', 'Lazio');
INSERT INTO public.location_area(id, code, description) VALUES(79, 'IT-Liguria', 'Liguria');
INSERT INTO public.location_area(id, code, description) VALUES(80, 'IT-Lombardia', 'Lombardia');
INSERT INTO public.location_area(id, code, description) VALUES(81, 'IT-Marche', 'Marche');
INSERT INTO public.location_area(id, code, description) VALUES(82, 'IT-Molise', 'Molise');
INSERT INTO public.location_area(id, code, description) VALUES(83, 'IT-Piemonte', 'Piemonte');
INSERT INTO public.location_area(id, code, description) VALUES(84, 'IT-Sardegna', 'Sardegna');
INSERT INTO public.location_area(id, code, description) VALUES(85, 'IT-Sicilia', 'Sicilia');
INSERT INTO public.location_area(id, code, description) VALUES(86, 'IT-Trentino-Alto Adige', 'Trentino-Alto Adige');
INSERT INTO public.location_area(id, code, description) VALUES(87, 'IT-Toscana', 'Toscana');
INSERT INTO public.location_area(id, code, description) VALUES(88, 'IT-Umbria', 'Umbria');
INSERT INTO public.location_area(id, code, description) VALUES(89, 'IT-Veneto', 'Veneto');
INSERT INTO public.location_area(id, code, description) VALUES(90, 'DE-Baden-Württemberg', 'Baden-Württemberg');
INSERT INTO public.location_area(id, code, description) VALUES(91, 'DE-Bavaria', 'Bavaria');
INSERT INTO public.location_area(id, code, description) VALUES(92, 'DE-Berlin', 'Berlin');
INSERT INTO public.location_area(id, code, description) VALUES(93, 'DE-Brandenburg', 'Brandenburg');
INSERT INTO public.location_area(id, code, description) VALUES(94, 'DE-Bremen', 'Bremen');
INSERT INTO public.location_area(id, code, description) VALUES(95, 'DE-Hamburg', 'Hamburg');
INSERT INTO public.location_area(id, code, description) VALUES(96, 'DE-Lower Saxony', 'Lower Saxony');
INSERT INTO public.location_area(id, code, description) VALUES(97, 'DE-Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern');
INSERT INTO public.location_area(id, code, description) VALUES(98, 'DE-North Rhine-Westphalia', 'North Rhine-Westphalia');
INSERT INTO public.location_area(id, code, description) VALUES(99, 'DE-Rhineland-Palatinate', 'Rhineland-Palatinate');
INSERT INTO public.location_area(id, code, description) VALUES(100, 'DE-Saarland', 'Saarland');
INSERT INTO public.location_area(id, code, description) VALUES(101, 'DE-Saxony', 'Saxony');
INSERT INTO public.location_area(id, code, description) VALUES(102, 'DE-Saxony-Anhalt', 'Saxony-Anhalt');
INSERT INTO public.location_area(id, code, description) VALUES(103, 'DE-Schleswig-Holstein', 'Schleswig-Holstein');
INSERT INTO public.location_area(id, code, description) VALUES(104, 'DE-Thuringia', 'Thuringia');
INSERT INTO public.location_area(id, code, description) VALUES(105, 'GR-Attica', 'Attica');
INSERT INTO public.location_area(id, code, description) VALUES(106, 'GR-Central Greece', 'Central Greece');
INSERT INTO public.location_area(id, code, description) VALUES(107, 'GR-Central Macedonia', 'Central Macedonia');
INSERT INTO public.location_area(id, code, description) VALUES(108, 'GR-Crete', 'Crete');
INSERT INTO public.location_area(id, code, description) VALUES(109, 'GR-Eastern Macedonia and Thrace', 'Eastern Macedonia and Thrace');
INSERT INTO public.location_area(id, code, description) VALUES(110, 'GR-Epirus', 'Epirus');
INSERT INTO public.location_area(id, code, description) VALUES(111,'GR-Ionian Islands', 'Ionian Islands');
INSERT INTO public.location_area(id, code, description) VALUES(112, 'GR-North Aegean', 'North Aegean');
INSERT INTO public.location_area(id, code, description) VALUES(113, 'GR-Peloponnese', 'Peloponnese');
INSERT INTO public.location_area(id, code, description) VALUES(114, 'GR-South Aegean', 'South Aegean');
INSERT INTO public.location_area(id, code, description) VALUES(115, 'GR-Thessaly', 'Thessaly');
INSERT INTO public.location_area(id, code, description) VALUES(116, 'GR-Western Greece', 'Western Greece');
INSERT INTO public.location_area(id, code, description) VALUES(117, 'GR-Western Macedonia', 'Western Macedonia');

INSERT INTO public.house_size(id, code, description) VALUES(1, 'S', '10 - 50 m2');
INSERT INTO public.house_size(id, code, description) VALUES(2, 'M', '50 - 100 m2');
INSERT INTO public.house_size(id, code, description) VALUES(3, 'L', '100 - 150 m2');


INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-1, '2017-07-10'::DATE, 'LT', 'NORD_POOL', 36);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-2, '2017-07-11'::DATE, 'LT', 'NORD_POOL', 38);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-3, '2017-07-12'::DATE, 'LT', 'NORD_POOL', 39);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-4, '2017-07-13'::DATE, 'LT', 'NORD_POOL', 45);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-5, '2017-07-14'::DATE, 'LT', 'NORD_POOL', 31);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-6, '2017-07-15'::DATE, 'LT', 'NORD_POOL', 33);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-7, '2017-07-16'::DATE, 'LT', 'NORD_POOL', 36);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-8, '2017-07-17'::DATE, 'LT', 'NORD_POOL', 38);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-9, '2017-07-18'::DATE, 'LT', 'NORD_POOL', 39);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-10, '2017-07-19'::DATE, 'LT', 'NORD_POOL', 45);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-11, '2017-07-20'::DATE, 'LT', 'NORD_POOL', 31);
INSERT INTO public.electricity_daily_price(id, date, region, source, unit_price) VALUES(-12, '2017-07-21'::DATE, 'LT', 'NORD_POOL', 33);